---
- name: Setup Docker repository.
  apt_repository: >
    repo="deb https://apt.dockerproject.org/repo debian-jessie main"
    state=present

- name: Setup Docker repository key.
  apt_key: >
    keyserver="hkp://p80.pool.sks-keyservers.net:80"
    id="58118E89F3A912897C070ADBF76221572C52609D"
    state=present

- name: Make sure the Docker packages are installed.
  apt: >
    pkg={{ item }} state=latest
  with_items:
    - docker-engine
    - python-docker
