---
apt_repositories:
  - deb http://ftp.us.debian.org/debian/ stable main contrib non-free
  - deb http://security.debian.org/ stable/security main contrib non-free
  - deb http://ftp.us.debian.org/debian/ testing main contrib non-free
  - deb http://security.debian.org/ testing/security main contrib non-free
  - deb http://ftp.us.debian.org/debian/ unstable main contrib non-free
  - deb http://ftp.us.debian.org/debian/ stable-backports main contrib non-free


apt_repositories_absent:

default_apt_repository: stable
apt_cache_valid_secs: 3600  # 1 hour

default_ssh_key_type: rsa
default_ssh_key_bits: 8192

default_password_length: 32
default_password_chars: ascii_letters,digits

swap_file_path: /swapfile.0
swap_file_size_mb: 512

sysctl_fs_file_max: 524288
sysctl_vm_dirty_writeback_centisecs: 5000
sysctl_net_core_somaxconn: 65535

system_limit_nofile_hard: 524288
system_limit_nofile_soft: 524288
