---

- name: "Install needed APT packages: from backports."
  apt:
    pkg:
      - mercurial
    state: latest
    default_release: stable
    install_recommends: no
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_secs }}"


- name: "Check if we need to handshake with HG server. TODO: change to ~/.ssh/known_hosts!"
  shell: grep -c {{ hg_repository_host }} /etc/ssh/ssh_known_hosts
  ignore_errors: True
  changed_when: False
  register: need_ssh_keyscan

- name: "Handshake with HG server. TODO: change to ~/.ssh/known_hosts!"
  shell: ssh-keyscan {{ hg_repository_host }} >> /etc/ssh/ssh_known_hosts
  when: need_ssh_keyscan|failed or (need_ssh_keyscan.stdout | int) < 1

- name: Clone repository.
  become_user: "{{ hg_project_username }}"
  hg: >
    repo={{ hg_repository_url }}
    dest={{ hg_clone_path }}
    purge=yes
  notify: "{{ hg_update_handler }}"
  tags:
    - source-updates-only
