---

- name: 'Setup ntp client.'
  apt:
    pkg:
      - ntp
    state: latest
    default_release: stable
    install_recommends: no
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_secs }}"
