---

# - name: apt-get may need the latest keys
#   apt_key: id={{ item }} state=present keyserver=subkeys.pgp.net
#   with_items:
#     - 9D6D8F6BC857C906
#     - 7638D0442B90D010

- name: Make sure all actual APT keys are present.
  apt: >
    pkg=debian-archive-keyring
    state=latest
    install_recommends=no
    update_cache=yes cache_valid_time={{ apt_cache_valid_secs }}

- name: apt_repository requires apt-related several packages to be installed.
  apt: >
    pkg={{item}}
    state=present
    install_recommends=no
    update_cache=yes cache_valid_time={{ apt_cache_valid_secs }}
  with_items:
      - python-apt
      - apt-transport-https
      - ca-certificates

- name: "Remove old repositories: 1/2."
  file: path=/etc/apt/sources.list state=absent

- name: "Remove old repositories: 2/2."
  apt_repository: repo="{{ item }}" state=absent
  with_items: "{{apt_repositories_absent}}"

- name: Setup APT repositories.
  apt_repository: repo="{{ item }}" state=present
  with_items: "{{apt_repositories}}"

- name: Setup APT settings.
  template: >
    src="etc/apt/preferences.d/repo-priorities.pref.j2"
    dest="/etc/apt/preferences.d/repo-priorities.pref"
    owner=root group=root mode=644
